### ISSUE TITLE
Add a checkbox to disable background notifications

### ISSUE THREAD

**Issue by Struppi1977** [cprcrack/WAToolkit#1]
In the extension no options are selected, they are highlighted in gray. You can not select the check box to receive notifications.

You can not specify that WhatsApp Web runs in the background and notifications will be permanently displayed until you have read it.

But the idea is good. Please continue!

**Comment by rubnvp** [comment]
yeah, also could be a good idea to add the option for silent notifications for "1 hour", "2 hours", "1 day" or "forever" :D

**Comment by cprcrack** [comment]
Background notifications can now be disabled in version 1.4
