### ISSUE TITLE
Learning

### ISSUE THREAD

**Issue by eemi2010** [cprcrack/WAToolkit#11]
Hi Great Extension.
I m studying the source to learn how to do  this type of things.
How you know when someone receives a new message ?
I looked at the code and simply cant spot it.

Thanks for your great work.

**Comment by cprcrack** [comment]
When a notification is intercepted: https://github.com/cprcrack/WAToolkit/blob/f7159f124a7b1c0b13f86f3a6aad140c4240c0c9/sources/script.js#L232

At any point, parsing the UI: https://github.com/cprcrack/WAToolkit/blob/f7159f124a7b1c0b13f86f3a6aad140c4240c0c9/sources/script.js#L313

**Comment by eemi2010** [comment]
You rock man. Thx. One has to activate desktop notification on whatsapp web for notification to work right ? That was the part I was missing. The extension does not do it

**Comment by cprcrack** [comment]
You are right.
