### ISSUE TITLE
Chrome icon context menu action

### ISSUE THREAD

**Issue by p-schneider** [cprcrack/WAToolkit#3]
The WAToolkit entry in the context menu of the Chrome tray icon does open a new tab with `chrome://extensions`. Is it possible to change it to open a new tab with `https://web.whatsapp.com/`?

![rightclicktraybar](https://cloud.githubusercontent.com/assets/2636101/6003171/bcb489e8-aaf9-11e4-88e0-be91e4e02144.png)

**Comment by cprcrack** [comment]
Probably yes, will look into it.

**Comment by p-schneider** [comment]
It is working well in release 1.4.
Thank you!
