### ISSUE TITLE
user-agent on Chromium

### ISSUE THREAD

**Issue by davidbaumann** [cprcrack/WAToolkit#6]
Is there a way to enable Whatsapp Web for Chromium users?
I think it should not be complicated to add a user-agent switcher, so chromium users can use it. It just needs so send Chrome as user-agent, when opening web.whatsapp.com

**Comment by dotlambda** [comment]
I'm using Chromium on Arch Linux and I have no problem using WhatsApp Web with the standard user agent, which for me is:
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36`
It seems like Chromium sends a Chrome user agent by default: http://stackoverflow.com/q/17391696
If this isn't the case for you and you don't want to install a user agent switcher extension, you can still use the `--user-agent` flag to set a custom one: https://wiki.archlinux.org/index.php/Chromium_tweaks#User_Agent
But ensure that you shut down Chromium completely (by clicking "Exit" in the system tray menu) before relaunching with the flag.

**Comment by davidbaumann** [comment]
On Ubuntu for me, it's
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko)
Ubuntu Chromium/40.0.2214.111 Chrome/40.0.2214.111 Safari/537.36

**Comment by dotlambda** [comment]
I think Canonical change the user agent in their package :disappointed:
You could write them (support@whatsapp.com) to tell them that your user agent isn't recognized correctly. And to work around the problem, the best solution probably is to modify the launcher command for Chromium: http://askubuntu.com/a/143807
Set it to something like `chromium --user-agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36"` and everything should work fine.

**Comment by davidbaumann** [comment]
This way, it actually works...
But it would be nice to have it integrated into WAToolkit.

**Comment by cprcrack** [comment]
I prefer not to support browsers that WhatsApp Web doesn't support by itself, so that I don't give WhatsApp Inc. any reason to be unhappy with WAToolkit. They proved to be quite strict in the past with third-party software so I aim to be very respectful.

As artiifix suggested, you can try to reach WhatsApp support about this.

**Comment by davidbaumann** [comment]
I tried to reach Thema, but I only got copy and paste answers.
