### ISSUE TITLE
Publish extension on Opera add-ons

### ISSUE THREAD

**Issue by dotlambda** [cprcrack/WAToolkit#7]
Because Opera is built on top of Chromium, you could easily publish the extension under https://addons.opera.com/. But there are a few issues to work out:
- the newTabUrl is either `opera://startpage/#speeddial` or `opera://startpage/#discover`
- the `#watOptions` fragment is set only rarely, so we'd have to find another trick
- References to "Chrome" should be removed, e.g. "Rate WAToolkit in Chrome Web Store"
- ...

Are you willing to publish WAToolkit on Opera add-ons?

**Comment by cprcrack** [comment]
Thanks for the analysis.

Currently I'm not thinking of porting WAToolkit into other browsers. I ported [another extension I developed](http://ratingspreview.com) from Chrome to Firefox and Safari and it was great for learning, but much more work than I expected, specially with regards to bugs and maintenance. Moreover, 95% of the users are still in the Chrome version.

As my free time is limited, this time I prefer to concentrate my efforts in the Chrome version, but anyone willing to fork and create a WAToolkit-Firefox/Opera will probably have it easy enough.
